In [1]:
%matplotlib inline
import numpy as np
import pandas as pd
import viz # curriculum example visualizations

np.random.seed(29)

In [2]:
n_trials = nrows = 10_000
n_dice = ncols = 3

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(nrows, ncols)
rolls

array([[6, 4, 5],
       [6, 3, 1],
       [1, 2, 2],
       ...,
       [6, 2, 1],
       [3, 4, 3],
       [4, 2, 4]])

In [3]:
#set the number of trials

n_trials = 10_000
n_rows = 10_000

#roll 3 dice

n_dice = 3
n_cols = 3

#use np's random choice
# Select from [1, 2, 3,4 5, 6]

rolls = np.random.choice([1, 2, 3, 4, 5, 6], n_trials * n_dice).reshape(n_rows, n_cols)

rolls

array([[6, 3, 4],
       [5, 3, 5],
       [6, 1, 3],
       ...,
       [4, 1, 3],
       [3, 6, 5],
       [3, 2, 6]])

In [19]:
sums_by_trial = rolls.sum(axis = 1)
sums_by_trial

array([13, 13, 10, ...,  8, 14, 11])

In [ ]:
viz.simulation_example1(sums_by_trial) #presents visualization of potential outcome

In [12]:
wins = sums_by_trial > 12
wins

array([ True,  True, False, ..., False,  True, False])

In [13]:
win_rate = wins.astype(int).mean()
win_rate

0.2552

In [14]:
#calculate expected winnings - $15 is the prive if you win
expected_winnings = win_rate * 15

#account for the price of the game, $5
cost = 5

#profit
expected_profit = expected_winnings - cost
expected_profit

-1.1720000000000002

In [15]:
wins = sums_by_trial >= 12
win_rate = wins.astype(int).mean()
expected_winnings = win_rate * 15
cost = 5
expected_profit = expected_winnings - cost
expected_profit

0.5484999999999998

### Naps

In [17]:
p_nap = .3
ndays = ncols = 2
n_simulated_weekends = nrows = 10**5

In [18]:
data = np.random.random((nrows, ncols))
data

array([[0.00946594, 0.69968646],
       [0.18109235, 0.45953643],
       [0.60421559, 0.85162938],
       ...,
       [0.649452  , 0.83324119],
       [0.12823097, 0.40461738],
       [0.11628656, 0.86938738]])

##### 5 min slot machine script

In [28]:
bal = 50000

In [59]:
import random as r
play = int(input("Enter your bet $"))
box = r.randint(1,11)
box
if box == 3:
    bal = bal + (play * 2)
    print(" You win 2X!")
    print("Your current balance is $" + str(bal))
elif box == 3:
    bal = bal + (play * 7)
    print(" Big win! 7X multiplier! ")
    print("Your current balance is $" + str(bal))
else:
    bal = bal - int(play)
    print(" Sorry! Try again! ")
    print("Your current balance is $" + str(bal))

        

Enter your bet $100
 You win! 
Your current balance is $48700
